---
kind: pipeline
type: ssh
name: 发布

server:
  host: 
    from_secret: host
  user: 
    from_secret: user
  password:
    from_secret: password

steps:
- name: ssh发布
  commands:
    - docker-compose down
    - git pull
    - docker-compose build 
    - docker-compose up -d
    - docker container prune -f
