CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "DialogCollection" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "UserName" character varying(50) NULL,
    "UserQQ" character varying(20) NULL,
    "Message" character varying(2000) NULL,
    "QuoteMessage" character varying(2000) NULL,
    "DateTime" timestamp without time zone NOT NULL,
    CONSTRAINT "PK_DialogCollection" PRIMARY KEY ("Id")
);

CREATE TABLE "User" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "QQ" character varying(20) NULL,
    "Preset" character varying(5000) NULL,
    "QQNickName" character varying(500) NULL,
    CONSTRAINT "PK_User" PRIMARY KEY ("Id")
);

CREATE TABLE "UserHistory" (
    "Id" bigint GENERATED BY DEFAULT AS IDENTITY,
    "Message" text NULL,
    "DateTime" timestamp without time zone NOT NULL,
    "UserId" bigint NOT NULL,
    "Role" text NULL,
    CONSTRAINT "PK_UserHistory" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_UserHistory_User_UserId" FOREIGN KEY ("UserId") REFERENCES "User" ("Id") ON DELETE CASCADE
);

CREATE UNIQUE INDEX "IX_User_QQ" ON "User" ("QQ");

CREATE INDEX "IX_UserHistory_UserId" ON "UserHistory" ("UserId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20230425123038_Init', '7.0.5');

COMMIT;

